"""Week 3: SRE Postmortem RAG Assistant FastAPI Application with Input Guardrails.

Serves the RAG pipeline with PII redaction and prompt-injection detection guardrails.
"""

from __future__ import annotations

import os
from collections.abc import AsyncGenerator
from contextlib import asynccontextmanager

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException, status
from pydantic import BaseModel, Field

from guardrails import detect_prompt_injection, redact_pii
from week1_rag import (
    PROJECT_ROOT,
    TOP_K,
    build_vector_store,
    format_context,
    generate_answer,
    load_corpus,
)


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncGenerator[None, None]:
    """Build the local vector store once on startup."""
    load_dotenv(PROJECT_ROOT / ".env")
    if not os.getenv("GROQ_API_KEY"):
        raise RuntimeError("GROQ_API_KEY is required. Add it to a local .env file.")

    print("Building local vector store on startup...")
    corpus = load_corpus()
    app.state.vector_store = build_vector_store(corpus)
    print(f"Vector store initialized with {len(corpus)} documents.")
    yield


app = FastAPI(
    title="SRE Postmortem RAG Assistant",
    description="A RAG assistant for querying SRE incident postmortems with input guardrails.",
    version="0.3.0",
    lifespan=lifespan,
)


class AskRequest(BaseModel):
    question: str = Field(
        ...,
        description="The incident question to ask the RAG assistant.",
        examples=[
            "What caused GitHub's DNS outage, and how did the response make the impact worse?"
        ],
    )


class AskResponse(BaseModel):
    answer: str = Field(..., description="The grounded answer generated by the assistant.")
    sources: list[str] = Field(..., description="List of unique source file names referenced.")
    model: str = Field(..., description="The LLM model used for generation.")
    pii_redacted: bool = Field(
        False, description="Whether PII was detected and redacted from the question."
    )


class HealthResponse(BaseModel):
    status: str = Field("ok", description="Server health status.")


@app.get("/health", response_model=HealthResponse, tags=["Health"])
async def health_check() -> HealthResponse:
    """Liveness check endpoint."""
    return HealthResponse(status="ok")


@app.post("/ask", response_model=AskResponse, tags=["RAG Assistant"])
async def ask(request: AskRequest) -> AskResponse:
    """Retrieve postmortem excerpts and generate a grounded answer after applying guardrails."""
    raw_question = request.question.strip()
    if not raw_question:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Question must not be empty.",
        )

    # 1. Prompt-Injection Guardrail
    is_injection, reason = detect_prompt_injection(raw_question)
    if is_injection:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Prompt injection attempt detected ({reason}). Request rejected.",
        )

    # 2. PII Redaction Guardrail
    sanitized_question, pii_redacted = redact_pii(raw_question)

    vector_store = getattr(app.state, "vector_store", None)
    if vector_store is None:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Vector store is not initialized.",
        )

    try:
        retrieved_docs = vector_store.similarity_search(sanitized_question, k=TOP_K)
        context = format_context(retrieved_docs)
        answer, model_used = generate_answer(sanitized_question, context)
        # Deduplicate sources while preserving order
        sources = list(dict.fromkeys(doc.metadata["source"] for doc in retrieved_docs))

        return AskResponse(
            answer=answer,
            sources=sources,
            model=model_used,
            pii_redacted=pii_redacted,
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while generating answer: {str(e)}",
        ) from e
