services:
  - type: web
    name: ai-sre-rag
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: LANGSMITH_API_KEY
        sync: false
      - key: LANGSMITH_ENDPOINT
        value: https://api.smith.langchain.com
      - key: LANGSMITH_TRACING
        value: "true"
      - key: LANGSMITH_PROJECT
        value: sre-postmortem-rag-prod
